In [4]:
#import modules for the analysis environment
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import datetime as dt

#read cleaned csv file
file_path = "Data/Clean/cleaned_data.csv"
df = pd.read_csv(file_path)
df.head()

date  time         area  district  victim_Age  \
0  2019-06-22T00:00:00.000  1150      Mission      1985        32.0   
1  2019-06-22T00:00:00.000  1600    Southwest       357        27.0   
2  2019-06-22T00:00:00.000   650  West Valley      1001        20.0   
3  2019-06-22T00:00:00.000   525      Topanga      2145        44.0   
4  2019-06-22T00:00:00.000   245  N Hollywood      1543        43.0   

  victim_sex victim_race  premise                          address  \
0          M    Hispanic    101.0  PARTHENIA                    ST   
1          M    Hispanic    101.0                        JEFFERSON   
2          F    Hispanic    101.0                           ROSCOE   
3          F    Hispanic    101.0  VICTORY                      BL   
4          F    Hispanic    101.0  LAUREL CANYON                BL   

                      cross_street      zip      lat       lon  
0  TOBIAS                       AV  19730.0  34.2279 -118.4516  
1                         CATALINA  22724.0  34.0255 -118.2937  
2                          SHIRLEY  18909.0  34.2204 -118.5579  
3  SHOUP                        AV   4278.0  34.1865 -118.6146  
4  MAGNOLIA                     BL   8890.0  34.1649 -118.3965

In [13]:
def main():
    dates, data = generate_data()
    fig, ax = plt.subplots(figsize=(6, 10))
    calendar_heatmap(ax, dates, data)
    plt.show()

def generate_data():
    num = 100
    data = np.random.randint(0, 20, num)
    start = dt.datetime(2015, 3, 13)
    dates = [start + dt.timedelta(days=i) for i in range(num)]
    return dates, data

def calendar_array(dates, data):
    i, j = zip(*[d.isocalendar()[1:] for d in dates])
    i = np.array(i) - min(i)
    j = np.array(j) - 1
    ni = max(i) + 1

    calendar = np.nan * np.zeros((ni, 7))
    calendar[i, j] = data
    return i, j, calendar


def calendar_heatmap(ax, dates, data):
    i, j, calendar = calendar_array(dates, data)
    im = ax.imshow(calendar, interpolation='none', cmap='summer')
    label_days(ax, dates, i, j, calendar)
    label_months(ax, dates, i, j, calendar)
    ax.figure.colorbar(im)

def label_days(ax, dates, i, j, calendar):
    ni, nj = calendar.shape
    day_of_month = np.nan * np.zeros((ni, 7))
    day_of_month[i, j] = [d.day for d in dates]

    for (i, j), day in np.ndenumerate(day_of_month):
        if np.isfinite(day):
            ax.text(j, i, int(day), ha='center', va='center')

    ax.set(xticks=np.arange(7), 
           xticklabels=['M', 'T', 'W', 'R', 'F', 'S', 'S'])
    ax.xaxis.tick_top()

def label_months(ax, dates, i, j, calendar):
    month_labels = np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul',
                             'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
    months = np.array([d.month for d in dates])
    uniq_months = sorted(set(months))
    yticks = [i[months == m].mean() for m in uniq_months]
    labels = [month_labels[m - 1] for m in uniq_months]
    ax.set(yticks=yticks)
    ax.set_yticklabels(labels, rotation=90)

dates,data=generate_data()
calendar_array(dates,data)

(array([ 0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
         5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
         7,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9, 10, 10,
        10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12,
        12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14]),
 array([4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
        5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
        6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
        0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
        1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5]),
 array([[nan, nan, nan, nan,  6.,  7.,  7.],
        [17.,  1.,  0.,  9.,  0.,  7.,  2.],
        [ 2., 14.,  3.,  6.,  3., 16.,  1.],
        [ 0.,  3., 13., 19., 16.,  7.,  5.],
        [ 2.,  0., 10., 15.,